name: Sync with Panel

on:
  push:
    branches:
      - main

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Deployment Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PANEL_URL: ${{ secrets.PANEL_URL }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
        run: |
          node scripts/sync.js
